### PR TITLE
Add support IPv6 sockets

### LINKED ISSUE #27: Containers don't listen on IPv6
`PublishPort` lines in the container file don't get properly translated for IPv6 sockets.

This container file:
```ini
[Unit]
Description=test container

[Container]
Image=httpd:latest
PublishPort=80:80
PublishPort=[::]:80:80

[Service]
Restart=always

[Install]
WantedBy=multi-user.target default.target
```

Should result in this service file:
```ini
# Automatically generated by quadlet-generator
[Unit]
Description=test container
RequiresMountsFor=%t/containers
SourcePath=/etc/containers/systemd/test.container

[X-Container]
Image=docker.io/httpd:latest
PublishPort=80:80
PublishPort=[::]:80:80

[Service]
Restart=always
Environment=PODMAN_SYSTEMD_UNIT=%n
KillMode=mixed
ExecStartPre=-rm -f %t/%N.cid
ExecStopPost=-/usr/bin/podman rm -f -i --cidfile=%t/%N.cid
ExecStopPost=-rm -f %t/%N.cid
Delegate=yes
Type=notify
NotifyAccess=all
SyslogIdentifier=%N
ExecStart=/usr/bin/podman run --name=systemd-%N --cidfile=%t/%N.cid --replace --rm -d --log-driver journald --pull=never --runtime /usr/bin/crun --cgroups=split --init --sdnotify=conmon --security-opt=no-new-privileges --cap-drop=all --mount type=tmpfs,tmpfs-size=512M,destination=/tmp --uidmap 0:0:1 --uidmap 1:1879048192:65536 --gidmap 0:0:1 --gidmap 1:1879048192:65536 -p=80:80 -p=[::]:80:80 docker.io/httpd:latest

[Install]
WantedBy=multi-user.target default.target
```

The `-p80:80` ends up there but not the `-p[::]:80:80`. I guess it's a parsing error when the conversion from `.container` to `.service` file happens.

### PR DESCRIPTION
**Pull request by XenGi**
fixes #27

### CODE REVIEW

**Comment by XenGi** [comment]
The problematic line is in `generator.c` :521

```
g_auto(GStrv) parts = g_strsplit (publish_port, ":", -1);
```

It splits the input at the `:` sign which break when an IPv6 address is entered because this introduces at minimum two new `:`s. I'm not sure how to do this the easiest way. The obvious solution would be to use a regex to parse the `PublishPort` string. But I'm not sure how to do that in C.

The regex I came up with goes like this:
```
^(?:(\[[a-f0-9:]+\]|[0-9]+.[0-9]+.[0-9]+.[0-9]+):)?(?:(\d+)?:)?(\d+)$
```

**Comment by XenGi** [comment]
Here's is another question. Quadlet does some validation on the port format. Is this really needed? I'm not sure but I think the corresponding error would show up in the kernel log and not in the journal of the systemd unit of the container.
Wouldn't it be better to just take the `PublishPort` string as is and let podman generate proper error messages in the journal?

**Comment by XenGi** [comment]
Let's say we still parse the parameter.
Using regex in C seems to be absolutely terrible. But I don't like C to begin with so this doesn't say much. To avoid regex another approach could be this:

- split publishport at `:` as before
- parse list of strings from the end
- first (last in list) string is always the inner port
- if second string exists and doesn't end with `]` or includes `.` aka is not an IP -> save as outer port (if empty string then == inner port)
- if third arg exists and has `.` -> save as IPv4
- if third arg exists and ends with `]` take the rest of args together and save as IPv6

I'll try writing this in C but I guess it won't be pretty.

**Comment by XenGi** [comment]
Turns out the code wasn't that hard to write. I simply reversed the PublishPort string and spitted it in maximum 3 parts. That way it's easy to detect IPv4 and IPv6 addresses. Test cases also work.
Would be pretty cool if you could merge this @alexlarsson

**Comment by alexlarsson** [comment]
New version rebased the commit to drop the intermediate steps.

**Comment by alexlarsson** [comment]
Broken CI seems to be some apt repo issue. Lets wait a bit and retry.

**Comment by XenGi** [comment]
Honestly I don't understand the new code. Seems to do some pointer magic I don't fully get. What exactly was the problem with my approach? I mean it's just a colon seperated string and the max parts argument to the split function perfectly works around the issue that IPv6 addresses have colons too.

**Comment by alexlarsson** [comment]
The new code just splits the parts taking the brackets into consideration, whereas the other code wasn't wrong per se, but it was kinda weird in how it did things. Its not like it didn't work for what it was doing, but the second you wanted to do some other kind of change to that code you would have to take into consideration that strings are reversed, and that the parts may be split weirdly.

Sorry for hijacking your PR though.

**Comment by alexlarsson** [comment]
The "pointer magic" is really just stepping through the characters of the string, its just weird because C is weird.

**Comment by alexlarsson** [comment]
WTH is up with the CI though...

**Comment by XenGi** [comment]
> Sorry for hijacking your PR though.

No problem. Just wanted to understand. I'm not into C because of its weirdness. ;)
But always eager to learn how it's done.

As long as I can use IPv6 afterwards, I'm happy. :)

**Comment by alexlarsson** [comment]
I assume this CI issue is some transient github actions repo thing. I'm gonna merge this as is, because it passes the tests locally at least.

**Pull request merged**
